
# main
max_fps: 15

# gui
window:
  position: [250, 80]
  size: [1050, 720]

board:
  length: 616

menu_button:
  size: [200, 60]
  text_size: 30
  color: "gray"

game_button:
  size: [130, 40]
  text_size: 22
  color: "gray"

turner:
  size: [275, 50]
  color: "blue"
  color_outline: "white"

logger:
  size: [275, 360]
  color: "blue"
  color_outline: "white"